### ISSUE TITLE
Terraform Implementation

### ISSUE THREAD

**Issue by mysticrenji** [Richard-Barrett/terraform-artifactory-scim-integration#1]
Hi @Richard-Barrett , 
Just waiting for the first commit on the implementation. This would be helpful for me, as I have similar use case.

**Comment by Richard-Barrett** [comment]
@mysticrenji it should be done, not sure if you have checked it out yet or not. I just caught this comment. Sorry I didn't get to it before hand. But if you have not checked it out yet, please do so, and feel free to open any issues:

- https://github.com/Richard-Barrett/terraform-snowflake-scim-integration.git

**Comment by Richard-Barrett** [comment]
Actually I realized I gave you my snowflake one, I will make this today.

**Comment by Richard-Barrett** [comment]
@mysticrenji give it a whirl:

- https://github.com/Richard-Barrett/terraform-artifactory-scim-integration

Feel free to open any issues if you come across issues.

**Comment by mysticrenji** [comment]
Thanks @Richard-Barrett , i will try it out!
